from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

"""
THIS CODE WAS CREATED TO DESIGN THE GUI FOR THE MAIN WINDOW
"""

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 650)
        MainWindow.setFocusPolicy(QtCore.Qt.WheelFocus)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LiveCameraFeed_Label = QtWidgets.QLabel(self.centralwidget)
        self.LiveCameraFeed_Label.setGeometry(QtCore.QRect(30, 140, 600, 400))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.LiveCameraFeed_Label.setFont(font)
        self.LiveCameraFeed_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.LiveCameraFeed_Label.setObjectName("LiveCameraFeed_Label")
        self.MainTitle_Label = QtWidgets.QLabel(self.centralwidget)
        self.MainTitle_Label.setGeometry(QtCore.QRect(30, 30, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setUnderline(True)
        self.MainTitle_Label.setFont(font)
        self.MainTitle_Label.setObjectName("MainTitle_Label")
        self.CameraControl_Label = QtWidgets.QLabel(self.centralwidget)
        self.CameraControl_Label.setGeometry(QtCore.QRect(680, 80, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setUnderline(True)
        self.CameraControl_Label.setFont(font)
        self.CameraControl_Label.setObjectName("CameraControl_Label")
        self.StageControl_Label = QtWidgets.QLabel(self.centralwidget)
        self.StageControl_Label.setGeometry(QtCore.QRect(680, 350, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setUnderline(True)
        self.StageControl_Label.setFont(font)
        self.StageControl_Label.setObjectName("StageControl_Label")
        self.X_Label = QtWidgets.QLabel(self.centralwidget)
        self.X_Label.setGeometry(QtCore.QRect(680, 390, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(False)
        self.X_Label.setFont(font)
        self.X_Label.setObjectName("X_Label")
        self.Y_Label = QtWidgets.QLabel(self.centralwidget)
        self.Y_Label.setGeometry(QtCore.QRect(680, 460, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(False)
        self.Y_Label.setFont(font)
        self.Y_Label.setObjectName("Y_Label")
        self.Z_Label = QtWidgets.QLabel(self.centralwidget)
        self.Z_Label.setGeometry(QtCore.QRect(680, 530, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(False)
        self.Z_Label.setFont(font)
        self.Z_Label.setObjectName("Z_Label")
        self.XPos_Button = QtWidgets.QPushButton(self.centralwidget)
        self.XPos_Button.setGeometry(QtCore.QRect(680, 430, 30, 30))
        self.XPos_Button.setObjectName("XPos_Button")
        self.YPos_Button = QtWidgets.QPushButton(self.centralwidget)
        self.YPos_Button.setGeometry(QtCore.QRect(680, 500, 30, 30))
        self.YPos_Button.setObjectName("YPos_Button")
        self.ZPos_Button = QtWidgets.QPushButton(self.centralwidget)
        self.ZPos_Button.setGeometry(QtCore.QRect(680, 570, 30, 30))
        self.ZPos_Button.setObjectName("ZPos_Button")
        self.XNeg_Button = QtWidgets.QPushButton(self.centralwidget)
        self.XNeg_Button.setGeometry(QtCore.QRect(720, 430, 30, 30))
        self.XNeg_Button.setObjectName("XNeg_Button")
        self.YNeg_Button = QtWidgets.QPushButton(self.centralwidget)
        self.YNeg_Button.setGeometry(QtCore.QRect(720, 500, 30, 30))
        self.YNeg_Button.setObjectName("YNeg_Button")
        self.ZNeg_Button = QtWidgets.QPushButton(self.centralwidget)
        self.ZNeg_Button.setGeometry(QtCore.QRect(720, 570, 30, 30))
        self.ZNeg_Button.setObjectName("ZNeg_Button")
        self.ActivateCamera_Button = QtWidgets.QPushButton(self.centralwidget)
        self.ActivateCamera_Button.setGeometry(QtCore.QRect(680, 130, 121, 28))
        self.ActivateCamera_Button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ActivateCamera_Button.setObjectName("ActivateCamera_Button")
        self.Autofocus_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Autofocus_Button.setGeometry(QtCore.QRect(810, 130, 90, 28))
        self.Autofocus_Button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Autofocus_Button.setObjectName("Autofocus_Button")
        self.CaptureImage_Button = QtWidgets.QPushButton(self.centralwidget)
        self.CaptureImage_Button.setGeometry(QtCore.QRect(680, 300, 121, 28))
        self.CaptureImage_Button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CaptureImage_Button.setObjectName("CaptureImage_Button")
        self.StartTimelapse_Button = QtWidgets.QPushButton(self.centralwidget)
        self.StartTimelapse_Button.setGeometry(QtCore.QRect(810, 300, 121, 28))
        self.StartTimelapse_Button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.StartTimelapse_Button.setObjectName("StartTimelapse_Button")
        self.StopTimelapse_Button = QtWidgets.QPushButton(self.centralwidget)
        self.StopTimelapse_Button.setGeometry(QtCore.QRect(940, 300, 121, 28))
        self.StopTimelapse_Button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.StopTimelapse_Button.setObjectName("StopTimelapse_Button")
        self.FileDirectory_Label = QtWidgets.QLabel(self.centralwidget)
        self.FileDirectory_Label.setGeometry(QtCore.QRect(680, 160, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setItalic(True)
        font.setUnderline(False)
        self.FileDirectory_Label.setFont(font)
        self.FileDirectory_Label.setObjectName("FileDirectory_Label")
        self.Sharpness_Label = QtWidgets.QLabel(self.centralwidget)
        self.Sharpness_Label.setGeometry(QtCore.QRect(30, 540, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setItalic(True)
        font.setUnderline(False)
        self.Sharpness_Label.setFont(font)
        self.Sharpness_Label.setObjectName("Sharpness_Label")
        self.SharpnessValue_Label = QtWidgets.QLabel(self.centralwidget)
        self.SharpnessValue_Label.setGeometry(QtCore.QRect(160, 540, 70, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setItalic(True)
        font.setUnderline(False)
        self.SharpnessValue_Label.setFont(font)
        self.SharpnessValue_Label.setObjectName("SharpnessValue_Label")
        self.TimelapseRun_Label = QtWidgets.QLabel(self.centralwidget)
        self.TimelapseRun_Label.setGeometry(QtCore.QRect(810, 320, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setItalic(True)
        font.setUnderline(False)
        self.TimelapseRun_Label.setFont(font)
        self.TimelapseRun_Label.setObjectName("TimelapseRun_Label")
        self.FileDirectory_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.FileDirectory_LineEdit.setGeometry(QtCore.QRect(680, 190, 371, 22))
        self.FileDirectory_LineEdit.setObjectName("FileDirectory_LineEdit")
        self.X_ComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.X_ComboBox.setGeometry(QtCore.QRect(830, 430, 41, 31))
        self.X_ComboBox.setObjectName("X_ComboBox")
        self.X_ComboBox.addItem("")
        self.X_ComboBox.addItem("")
        self.X_ComboBox.addItem("")
        self.X_ComboBox.addItem("")
        self.X_ComboBox.addItem("")
        self.StepNo_Label = QtWidgets.QLabel(self.centralwidget)
        self.StepNo_Label.setGeometry(QtCore.QRect(800, 390, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(False)
        self.StepNo_Label.setFont(font)
        self.StepNo_Label.setObjectName("StepNo_Label")
        self.Y_ComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.Y_ComboBox.setGeometry(QtCore.QRect(830, 500, 41, 31))
        self.Y_ComboBox.setObjectName("Y_ComboBox")
        self.Y_ComboBox.addItem("")
        self.Y_ComboBox.addItem("")
        self.Y_ComboBox.addItem("")
        self.Y_ComboBox.addItem("")
        self.Y_ComboBox.addItem("")
        self.Z_ComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.Z_ComboBox.setGeometry(QtCore.QRect(830, 570, 41, 31))
        self.Z_ComboBox.setObjectName("Z_ComboBox")
        self.Z_ComboBox.addItem("")
        self.Z_ComboBox.addItem("")
        self.Z_ComboBox.addItem("")
        self.Z_ComboBox.addItem("")
        self.Z_ComboBox.addItem("")
        self.Position_Label = QtWidgets.QLabel(self.centralwidget)
        self.Position_Label.setGeometry(QtCore.QRect(940, 390, 150, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(False)
        self.Position_Label.setFont(font)
        self.Position_Label.setObjectName("Position_Label")
        self.Recalibrate_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Recalibrate_Button.setGeometry(QtCore.QRect(960, 615, 100, 28))
        self.Recalibrate_Button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Recalibrate_Button.setObjectName("Recalibrate_Button")
        self.XPos_Label = QtWidgets.QLabel(self.centralwidget)
        self.XPos_Label.setGeometry(QtCore.QRect(970, 430, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.XPos_Label.setFont(font)
        self.XPos_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.XPos_Label.setObjectName("XPos_Label")
        self.YPos_Label = QtWidgets.QLabel(self.centralwidget)
        self.YPos_Label.setGeometry(QtCore.QRect(970, 500, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.YPos_Label.setFont(font)
        self.YPos_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.YPos_Label.setObjectName("YPos_Label")
        self.ZPos_Label = QtWidgets.QLabel(self.centralwidget)
        self.ZPos_Label.setGeometry(QtCore.QRect(970, 570, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.ZPos_Label.setFont(font)
        self.ZPos_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.ZPos_Label.setObjectName("ZPos_Label")
        self.CaptureNo_Spinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.CaptureNo_Spinbox.setGeometry(QtCore.QRect(890, 230, 160, 22))
        self.CaptureNo_Spinbox.setObjectName("CaptureNo_Spinbox")
        self.TimeStep_Spinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.TimeStep_Spinbox.setGeometry(QtCore.QRect(890, 260, 160, 22))
        self.TimeStep_Spinbox.setObjectName("TimeStep_Spinbox")
        self.CaptureNo_Label = QtWidgets.QLabel(self.centralwidget)
        self.CaptureNo_Label.setGeometry(QtCore.QRect(690, 220, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(False)
        self.CaptureNo_Label.setFont(font)
        self.CaptureNo_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.CaptureNo_Label.setObjectName("CaptureNo_Label")
        self.TimeStep_Label = QtWidgets.QLabel(self.centralwidget)
        self.TimeStep_Label.setGeometry(QtCore.QRect(690, 250, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setUnderline(False)
        self.TimeStep_Label.setFont(font)
        self.TimeStep_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.TimeStep_Label.setObjectName("TimeStep_Label")
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.TimeStep_Spinbox.setMaximum(10000000)
        self.TimeStep_Spinbox.setMinimum(1000)
        self.TimeStep_Spinbox.setSingleStep(1)
        
        self.CaptureNo_Spinbox.setMaximum(1000)
        self.CaptureNo_Spinbox.setMinimum(1)
        self.CaptureNo_Spinbox.setSingleStep(1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Live GUI"))
        self.LiveCameraFeed_Label.setText(_translate("MainWindow", "Live Camera Feed Presented In This Space"))
        self.MainTitle_Label.setText(_translate("MainWindow", "MICROSCOPE CONTROL GUI"))
        self.CameraControl_Label.setText(_translate("MainWindow", "CAMERA CONTROL"))
        self.StageControl_Label.setText(_translate("MainWindow", "STAGE CONTROL"))
        self.X_Label.setText(_translate("MainWindow", "X Direction"))
        self.Y_Label.setText(_translate("MainWindow", "Y Direction"))
        self.Z_Label.setText(_translate("MainWindow", "Z Direction"))
        self.XPos_Button.setText(_translate("MainWindow", "+"))
        self.YPos_Button.setText(_translate("MainWindow", "+"))
        self.ZPos_Button.setText(_translate("MainWindow", "+"))
        self.XNeg_Button.setText(_translate("MainWindow", "-"))
        self.YNeg_Button.setText(_translate("MainWindow", "-"))
        self.ZNeg_Button.setText(_translate("MainWindow", "-"))
        self.ActivateCamera_Button.setText(_translate("MainWindow", "Activate Camera"))
        self.Autofocus_Button.setText(_translate("MainWindow", "Autofocus"))
        self.CaptureImage_Button.setText(_translate("MainWindow", "Capture Image"))
        self.StartTimelapse_Button.setText(_translate("MainWindow", "Start Timelapse"))
        self.StopTimelapse_Button.setText(_translate("MainWindow", "Abort Timelapse"))
        self.FileDirectory_Label.setText(_translate("MainWindow", "Insert file directory in which the file is saved"))
        self.Sharpness_Label.setText(_translate("MainWindow", "Image sharpness value:"))
        self.SharpnessValue_Label.setText(_translate("MainWindow", "N/A"))
        self.TimelapseRun_Label.setText(_translate("MainWindow", ""))
        self.X_ComboBox.setItemText(0, _translate("MainWindow", "1"))
        self.X_ComboBox.setItemText(1, _translate("MainWindow", "5"))
        self.X_ComboBox.setItemText(2, _translate("MainWindow", "10"))
        self.X_ComboBox.setItemText(3, _translate("MainWindow", "20"))
        self.X_ComboBox.setItemText(4, _translate("MainWindow", "30"))
        self.StepNo_Label.setText(_translate("MainWindow", "Number of Steps"))
        self.Y_ComboBox.setItemText(0, _translate("MainWindow", "1"))
        self.Y_ComboBox.setItemText(1, _translate("MainWindow", "5"))
        self.Y_ComboBox.setItemText(2, _translate("MainWindow", "10"))
        self.Y_ComboBox.setItemText(3, _translate("MainWindow", "20"))
        self.Y_ComboBox.setItemText(4, _translate("MainWindow", "30"))
        self.Z_ComboBox.setItemText(0, _translate("MainWindow", "1"))
        self.Z_ComboBox.setItemText(1, _translate("MainWindow", "5"))
        self.Z_ComboBox.setItemText(2, _translate("MainWindow", "10"))
        self.Z_ComboBox.setItemText(3, _translate("MainWindow", "20"))
        self.Z_ComboBox.setItemText(4, _translate("MainWindow", "30"))
        self.Position_Label.setText(_translate("MainWindow", "Current Position (microns)"))
        self.Recalibrate_Button.setText(_translate("MainWindow", "Recalibrate"))
        self.XPos_Label.setText(_translate("MainWindow", "0"))
        self.YPos_Label.setText(_translate("MainWindow", "0"))
        self.ZPos_Label.setText(_translate("MainWindow", "0"))
        self.CaptureNo_Label.setText(_translate("MainWindow", "Total Number Of Captures"))
        self.TimeStep_Label.setText(_translate("MainWindow", "Intermediate Timestep (ms)"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())